target("smg-pc-render")
    set_kind("static")
    add_files("**.cpp")
    add_headerfiles("**.hpp")
    add_includedirs("./", { public = true })
    add_packages("bgfx", "stb", "glfw")
    add_deps("smg-pc-common")
