target("smg-pc-render")
    set_kind("static")
    add_files("RendererService.cpp")
    add_files("backends/**.cpp")
    add_files("capture/**.cpp")
    add_headerfiles("RendererService.hpp")
    add_headerfiles("backends/**.hpp")
    add_headerfiles("capture/**.hpp")
    add_headerfiles("core/**.hpp")
    add_headerfiles("shaders/**.hpp")
    add_includedirs("./", { public = true })
    add_packages("bgfx", "glfw", { public = true })
    add_deps("smg-pc-common")
