local encoding = dofile("scripts/source_mirror_encoding.lua")
local count = 0
local function check(original, native, expected)
    count = count + 1
    assert((original == native or original == encoding.normalize(native)) == expected, "Source boundary case " .. count)
end
check('f("日本語");\n', '#include "compat/Cp932Literal.hpp"\nf(CP932("日本語"));\n', true)
check('f("日" "本");', 'f(CP932("日" "本"));', true)
check('f("日" /* retained */\n"本");', 'f(CP932("日" /* retained */\n"本"));', true)
check('f("日\\"本\\n");', 'f(CP932("日\\"本\\n"));', true)
check('f("日本");', 'f(CP932 ( "日本" ));', true)
check('f(value);', 'f(CP932(value));', false)
check('f("日" + suffix);', 'f(CP932("日" + suffix));', false)
check('f("日", 2);', 'f(CP932("日", 2));', false)
check('f("日");', 'f(CP932("日");', false)
check('f("日");', 'f(CP932(CP932("日")));', false)
check('f("日");', 'g(CP932("日"));', false)
check('f("日", 1);', 'f(CP932("日"), 2);', false)
check('f("日");', 'f(CP932("本"));', false)
check('f("日");', 'f(CP932("\\x93\\xfa"));', false)
check('f("日");', 'f(MY_CP932("日"));', false)
check('f("日");', 'f(CP932_extra("日"));', false)
check('f("日"_tag);', 'f(CP932("日"_tag));', false)
check('f(u8"日");', 'f(CP932(u8"日"));', false)
check('f(L"日");', 'f(CP932(L"日"));', false)
check('// "日"\nf();', '// CP932("日")\nf();', false)
check('/* "日" */', '/* CP932("日") */', false)
check('// \\\n"日"\nf();', '// \\\nCP932("日")\nf();', false)
check('auto s = R"tag("日")tag";', 'auto s = R"tag(CP932("日"))tag";', false)
check('f("CP932(\\"日\\")");', 'f("CP932(\\"日\\")");', true)
check('int n = 1;\n', '#include "compat/Other.hpp"\nint n = 1;\n', false)
check('int n = 1;\n', '#include "compat/Cp932Literal.hpp"\n#include "compat/Cp932Literal.hpp"\nint n = 1;\n', false)
check('int n = 1;\n', 'int n = 1;\n#include "compat/Cp932Literal.hpp"\n', false)
check('int n = 1;\n', '#include "compat/Cp932Literal.hpp" // unexpected\nint n = 1;\n', false)
check('int n = 1;\n', '#include "compat/Cp932Literal.hpp"\n\nint n = 1;\n', false)
check('f("日"); // original', 'f(CP932("日")); // changed', false)
check('f("日");', 'f(CP932("日" /* unexpected */));', false)
print("Passed " .. count .. " strict Lua CP932 source-boundary cases")
