from pathlib import Path
import json,re,collections,hashlib,subprocess
root=Path.cwd();notes=root/'notes/compat-whole-surface-20260925'
scan=json.loads((notes/'render-effects-source-scan.json').read_text()); configs={}
def cfg(names,dest,action,deps,confidence='high',disposition='restore-original-owner'):
 for name in names.split():configs[name]={'disposition':disposition,'destination':dest.split(),'action':action,'dependencies':deps.split(';'),'confidence':confidence}
cfg('J3DAdditionalAnimationCompat.cpp J3DMaterialAnimationCompat.cpp J3DTransformAnimationCompat.cpp J3DFrameCtrlCompat.cpp J3DAnimationInterpolation.hpp','src/JSystem/J3DGraphAnimator/J3DAnimation.cpp','Reunify original animation implementation. Retain explicit PPC truncate/shift/narrow operations through Aurora and signed-16 scalar Hermite/FMA order at the canonical sampler; delete split compat providers/header. FrameCtrl edits are enum/name/control-flow rewriting, not a host boundary.','Coordinate all animation fragments to prevent duplicate bodies;resource/J3dAnimationResource native relocation;aurora/ppc_math.hpp;retain appropriate fp-contract flags')
cfg('J3DAnmLoaderCompat.cpp','src/JSystem/J3DGraphLoader/J3DAnmLoader.cpp src/resource/J3dAnimationResource.cpp','Restore loader ownership. Keep bounded native block relocation and registered resource lifetime entry at the loader/resource boundary; retain uintptr_t address arithmetic. Replace outdated readAnm dispatch wrappers with current donor setAnm dispatch when headers align.','J3dAnimationResource allocation/lifetime;native first/next_animation_block;canonical J3DAnimation class layouts')
cfg('J3DClusterCompat.cpp','src/JSystem/J3DGraphAnimator/J3DCluster.cpp','Return seven exact normalized original cluster/deform bodies to their canonical translation unit; delete the compat fragment.','J3DModel and vertex buffers;current donor headers')
cfg('J3DDrawBufferCompat.cpp','src/JSystem/J3DGraphBase/J3DDrawBuffer.cpp','Restore original sort/packet traversal as one canonical owner; current differences are null/cast spellings. Retain native pointer-width hash expression.','J3DPacket providers;J3DTexture pointers')
cfg('J3DDrawInitCompat.cpp J3DSysCompat.cpp','src/JSystem/J3DGraphBase/J3DSys.cpp','Reunify J3DSys globals, constructor, register initialization, and texture cache setup from original. Current donor diffs are spellings/locals.','Coordinate both fragments and any existing j3dSys static definition;Aurora GX state')
cfg('J3DGDCompat.cpp','src/JSystem/J3DGraphBase/J3DGD.cpp','Restore canonical J3D command writer owner; preserve explicit byte-oriented command writes and actual Aurora GD capacity/device behavior. Resolve helper inlines against current headers instead of another provider.','J3DGD header inline definitions;Aurora GD/FIFO;J3DMatBlock shared helpers')
cfg('J3DHierarchyCompat.cpp J3DJointTreeCompat.cpp','src/JSystem/J3DGraphAnimator/J3DJointTree.cpp src/JSystem/J3DGraphBase/J3DVertex.cpp','Restore exact makeHierarchy and joint-tree initialization/calculation to canonical owner; J3DDrawMtxData constructor belongs J3DVertex.','J3DJoint recursive calculator;native loader pointer relocation;OriginalJ3dJointTree bridge')
cfg('J3DJointCompat.cpp','src/JSystem/J3DGraphAnimator/J3DJoint.cpp src/JSystem/J3DGraphBase/J3DTransform.cpp src/JSystem/JMath/JMath.cpp','Split original Joint methods and translate-rotate helpers back to their genuine owners. Keep scalar reciprocal adaptation in JMath/Aurora PPC math, not a joint shim.','J3DJointEntryCompat must merge same owner;JMATrigonometric table;Aurora PPC reciprocal semantics')
cfg('J3DJointEntryCompat.cpp','src/JSystem/J3DGraphAnimator/J3DJoint.cpp','Restore original entryIn packet traversal with current donor return semantics; remove redundant u8 cast unless class signature still requires it.','J3DJointCompat same TU;draw buffer and material packet')
cfg('J3DMatBlockCompat.cpp','src/JSystem/J3DGraphBase/J3DMatBlock.cpp','Restore canonical block implementations (135 of 146 detected bodies are exact normalized donor). Preserve explicit big-endian packed color reads. Restore LightOn::diff donor light-mask dispatch; compat currently omits diffLight and all light mask bits. Reconcile helper/header providers before importing full TU.','J3DGD helpers;J3DTevs defaults;current ColorBlock headers;light/material GPU validation')
cfg('J3DMaterialAnmCompat.cpp','src/JSystem/J3DGraphAnimator/J3DMaterialAnm.cpp','Restore seven exact original material animation attachment/calculation bodies to canonical owner.','J3DAnimation owner;material blocks')
cfg('J3DMaterialAttachCompat.cpp J3DMaterialHelpersCompat.cpp','src/JSystem/J3DGraphAnimator/J3DMaterialAttach.cpp src/JSystem/J3DGraphBase/J3DMaterial.cpp','Restore exact original methods at per-symbol donor locations, not a new aggregate file. MaterialAttach and Material helper names are not ownership boundaries.','Per-symbol donor map in evidence;coordinate J3DMaterialFactoryCompat and MaterialVariants')
cfg('J3DMaterialFactoryCompat.cpp J3DMaterialVariantsCompat.cpp','src/JSystem/J3DGraphBase/J3DMaterial.cpp','Restore original J3DMaterial block factories and Patched/Locked variants to canonical material owner; detected bodies match donor.','MaterialHelpers same owner;J3DMatBlock class providers')
cfg('J3DMaterialLoaderFactoryCompat.cpp','src/JSystem/J3DGraphLoader/J3DMaterialFactory.cpp','Restore canonical material loader/factory; retain native-width relocation. Nonexact body changes are mostly spellings/local simplifications, but restore current mInfo-only assignment in modifyPatchedCurrentMtx.','J3dModelResource material block decoding;JSUConvertOffsetToPtr;native sizeof layout and allocation')
cfg('J3DModelCompat.cpp','src/JSystem/J3DGraphAnimator/J3DModel.cpp src/JSystem/J3DGraphAnimator/J3DModel.hpp','Restore original J3DModel provider, preserving coherent error propagation. Current donor has an inline empty J3DModel destructor in libs/JSystem/include; native src/Game/Player/J3DModelX.cpp has another out-of-line definition. Reconcile those providers by returning destructor to canonical header/class; do not preserve a duplicate.','J3DPacket canonical provider;J3DMtxBuffer;native renderer model ownership')
cfg('J3DModelDataCompat.cpp','src/JSystem/J3DGraphAnimator/J3DModelData.cpp src/JSystem/J3DGraphBase/J3DVertex.cpp','Restore original ModelData methods and VertexData constructor at actual owners; reconcile model-resource teardown before replacing empty destructor.','Native resource storage owns relocated model arrays;J3DJointTree;current headers')
cfg('J3DModelLoaderCompat.cpp J3DModelLoaderCompat.hpp','src/JSystem/J3DGraphLoader/J3DModelLoader.cpp src/resource/J3dModelResource.cpp','Replace detached finalize_j3d_model and copied setup_bboard_info with canonical loader finalization over validated native structures. Keep bounds/endian/relocation in existing resource decoder and explicit archive registration boundary. Delete compat forwarding header.','J3dModelResource construction calls finalize_j3d_model;original hierarchy/shape-table methods;BDL pointer conversion')
cfg('J3DMtxBufferCompat.cpp','src/JSystem/J3DGraphAnimator/J3DMtxBuffer.cpp','Restore canonical matrix-buffer implementation. Keep scalar weighted-envelope FMA sequence replacing PPC paired-single code; donor MW asm is not portable native implementation.','J3DJointTree envelope tables;Aurora PPC math;native matrix allocations')
cfg('J3DPacketCompat.cpp','src/JSystem/J3DGraphBase/J3DPacket.cpp','Restore canonical entire Packet TU and donor newDifferedDisplayList error return. Compat currently sets non-success result to zero; its eight-entry register table with a seven-iteration loop also drops indirect-stage budget and adds an unsupported ambient entry relative to current donor seven-entry table. Preserve original SDK interrupt/GD calls. No game-specific branch is needed.','J3DPacket.hpp return signature currently int vs donor J3DError;canonical build inclusion;external J3dCommandScope protects native entry;do not duplicate static GDL globals')
cfg('J3DShapeCompat.cpp','src/JSystem/J3DGraphBase/J3DShape.cpp','Restore canonical Shape behavior; retain GXSetArrayBase native-pointer API instead of truncating a pointer into a 32-bit CP address. Delegate encoding to Aurora.','Aurora GXSetArrayBase;J3DShapeDraw;native decoded arrays')
cfg('J3DShapeDrawCompat.cpp','src/JSystem/J3DGraphBase/J3DShapeDraw.cpp','Restore canonical display-list vertex counting/rewriting while retaining explicit big-endian u16 reads/writes and uintptr_t byte ranges.','Big-endian display-list bytes;GXCallDisplayList;native aligned allocation')
cfg('J3DShapeFactoryCompat.cpp','src/JSystem/J3DGraphLoader/J3DShapeFactory.cpp','Restore canonical shape factory with required sizeof(native object/pointer) accounting replacing Wii literal sizes.','J3D native class layouts;J3dModelResource shape relocation')
cfg('J3DShapeMtxCompat.cpp','src/JSystem/J3DGraphBase/J3DShapeMtx.cpp','Restore canonical matrix loaders and texture calculation. Retain real scalar overlap-safe 3x3 copy where current donor only has MW assembler.','J3DTransform functions;Game/System/Overwrite owns loadMtxIndx_PNGP;Aurora matrix APIs')
cfg('J3DShapeMtxGameCompat.cpp','src/Game/System/Overwrite.cpp','Restore SMG original J3DShapeMtx::loadMtxIndx_PNGP override to Game/System/Overwrite.cpp, including ShapePacketUserData texture matrices. It is original game behavior despite J3D symbol ownership.','Original Overwrite donor:232;avoid J3DShapeMtx library duplicate;ShapePacketUserData')
cfg('J3DShapeTableCompat.cpp','src/JSystem/J3DGraphAnimator/J3DShapeTable.cpp','Restore both exact original shape-table bodies.','Native loader finalization;J3DShape provider')
cfg('J3DSkinDeformCompat.cpp','src/JSystem/J3DGraphAnimator/J3DSkinDeform.cpp','Restore exact original skin-deform provider and preserve intentionally empty original VtxColorCalc body if placed there by donor; do not label original empty code a PC workaround.','Per-symbol donor paths;model update deformation')
cfg('J3DStructCompat.cpp','src/JSystem/J3DGraphBase/J3DStruct.cpp','Restore struct copying operators at canonical owner, preserving scalar assignments replacing PPC copy/stores and overlap order.','JMath gekko scalar copy functions;native class layouts')
cfg('J3DTevsCompat.cpp J3DTexMtxCompat.cpp','src/JSystem/J3DGraphBase/J3DTevs.cpp','Reunify canonical lighting/texture-number/texture-matrix command methods. Preserve endian packed display-list reads; restore donor signed s8 LOD interpretation in loadTexNo.','J3DGD and texture state;Aurora endian/GX;coordinate both fragments')
cfg('J3DTextureMtxCompat.cpp J3DTransformMtxCompat.cpp','src/JSystem/J3DGraphBase/J3DTransform.cpp src/JSystem/J3DGraphBase/J3DShapeMtx.cpp','Reunify original transform methods with PPC scalar/FMA implementations beside the original owner. Copy33From34 belongs ShapeMtx. Retain lookup-table trig and documented alias/store order.','JMath reciprocal and trig;Aurora matrix functions;joint translate-rotate fragment shares Transform TU')
cfg('J3DVertexBufferCompat.cpp','src/JSystem/J3DGraphBase/J3DVertex.cpp','Restore original VertexBuffer arrays and frame initialization. Differences are pointer getters/parameter names.','VertexData and DrawMtxData constructors from other fragments;J3DModel')
cfg('ActorShadowCsvCompat.cpp ActorShadowCsvCompat.hpp OriginalActorShadowQueries.cpp','src/Game/Util/ActorShadowUtil.cpp src/Game/Util/ActorShadowLocalUtil.cpp','Restore original JMapInfo CSV dispatch, all ten drawer kinds, controller defaults and query methods. Delete parallel Bcsv-to-ActorShadowRuntimeState algorithm and adapter API once callers use original resource holder/parser. Keep CP932 conversion only at literal/resource boundary.','ResourceHolder/JMapInfo original parser support;LiveActor::initShadowControllerList;restore missing drawer classes;ShadowControllerOwnership elimination')
cfg('ShadowControllerOwnership.cpp ShadowControllerOwnership.hpp','src/Game/LiveActor/ShadowController.cpp src/Game/LiveActor/LiveActor.cpp','Replace host definition replay/factory switch and shadow side owner with original ActorShadow creation; put only list/drawer destruction, holder unlink, stable borrowed-name ownership, and joint-matrix invalidation in owning Game classes.','ActorRuntimeRegistry shadow metadata and provider functions must retire;NameObj ownership capture;all ten drawer class implementations;scene heap lifetime','high','narrow-game-adaptation')
cfg('CapturedFrameBlurService.cpp CapturedFrameBlurService.hpp','src/Game/Screen/FullScreenBlur.cpp src/Game/Screen/CaptureScreenDirector.cpp aurora/lib/gx','Restore original blur draw/history algorithm; delete scene service and statistics API. Current service replaces EFB scratch rows/scissor offset with an offscreen target, first-frame history gating, fixed 608 coordinates, and does not restore camera projection/view like donor. Resolve EFB copy/scissor semantics generally in Aurora; if an unavoidable effect-specific fallback remains, keep it explicitly in FullScreenBlur owner.','GX EFB scratch region y464 and scissor offset1584 semantics;TDDraw;getFullScreenBlurTexture/nonFilteredCapture;CenterScreenBlurRealOrAbsentTests currently asserts service','medium','needs-investigation')
cfg('DrawSyncManagerLifetime.cpp DrawSyncManagerLifetime.hpp','src/Game/System/DrawSyncManager.cpp src/Game/System/GameSystem.cpp','Move native retained-heap lifetime and quiesce/retire callbacks into original DrawSyncManager/GameSystem ownership. Preserve actual manager queues/ranges/worker, callback drain before destruction and transactional failure rollback; do not recreate a parallel dispatcher.','Aurora guest threads/GX drain;JKR mapped heap owner;StarPointerDepthOwnership and scene retirement callers','high','narrow-game-adaptation')
cfg('EffectSystemOwnership.cpp EffectSystemOwnership.hpp','src/Game/Effect/EffectSystem.cpp src/Game/Effect/MultiEmitter.cpp src/Game/LiveActor/EffectKeeper.cpp src/Game/Screen/PaneEffectKeeper.cpp','Replace external effect ownership maps with owning Game destructors/initializers; retain required borrowed-callback retirement before freeing Keepers and nested effect allocations. Use actual GameSystem catalog/scene heap; remove standalone alternate resource branch when fixtures are migrated.','LiveActor/LayoutActor teardown;JPABaseEmitter pointer-width mpUserWork and last-owner retirement;SceneObjHolder factory;JKR allocation domains','high','narrow-game-adaptation')
cfg('ImageEffectOwnership.cpp ImageEffectOwnership.hpp','src/Game/Screen/ImageEffectDirector.cpp src/Game/Screen/ImageEffectSystemHolder.cpp src/Game/Screen/BloomEffect.cpp src/Game/Screen/BloomEffectSimple.cpp src/Game/Screen/DepthOfFieldBlur.cpp src/Game/Map/WaterAreaHolder.cpp','Replace six-ID external ownership/capture switch with owning-class destruction and original SceneObj factory. Retain actual textures/arrays/states finalization at those owners. Delete construction-time special manager once ownership explicit.','JUTTexture lifetime;SceneObjHolder rollback;screen child/state ownership;NameObj registration','high','narrow-game-adaptation')
cfg('JutTextureAllocation.cpp JutTextureAllocation.hpp','src/JSystem/JUtility/JUTTexture.cpp src/resource/Mem1ResourceHeap.cpp','Consolidate texture storage/lease allocation into canonical JUTTexture host implementation (currently runtime/jut/JutTexture.cpp), with resource heap as general mapped allocator. Prefer explicit owned storage in native JUTTexture over process side map; preserve GXDestroyCopyTex and draining-before-reuse.','RuntimeContext installs graphics heap;CaptureScreenDirector currently adopts via get_owned_jut_texture;Aurora GX copy tracking;native JUTTexture fields')
cfg('JutTextureConstruction.cpp JutTextureConstruction.hpp','src/JSystem/JUtility/JUTTexture.cpp src/Game/Screen/ImageEffectDirector.cpp','Delete generic texture construction interception once real owning Game classes destroy their textures. If exception-safe construction tracking is still necessary, keep it private to canonical JUTTexture owner; never retain a separate compat adoption manager.','ImageEffectOwnership retirement;SceneObjHolder rollback;native JUTTexture constructors/destructor currently call record/forget hooks','medium','narrow-game-adaptation')
cfg('J3dCommandScope.cpp J3dCommandScope.hpp SceneJ3dScope.hpp','src/JSystem/J3DGraphBase/J3DSys.hpp src/JSystem/J3DGraphBase/J3DSys.cpp','Give the J3DSys host owner explicit serialized context scopes for native entry, including original MR mutexes, GD pointer, interrupts and traversal globals. Preserve exception-safe recursive unlock. These scopes are general adaptations but no separate compat directory/API remains.','ResourceHolder and MarioAnimator native entry;RuntimeContext/SceneScheduler phases;Aurora guest thread scheduling;original MutexHolder global lock order')
cfg('J3dSystemCompat.cpp J3dSystemCompat.hpp','','Delete unused view-matrix forwarders and unused DrawUtil include; source references find declarations/definitions only. Original draw paths already access actual j3dSys.mViewMtx.','Remove src/Game/Util/DrawUtil.cpp unused include;check tests/build includes before delete','high','delete-unused')
cfg('LightDirectorCompat.cpp LightFunctionCompat.cpp LightFunctionCompat.hpp LightUtilCompat.cpp','src/Game/Map/LightDirector.cpp src/Game/Map/LightFunction.cpp src/Game/Map/LightDataHolder.cpp src/Game/Map/LightZoneDataHolder.cpp src/Game/Util/LightUtil.cpp','Restore original archive/BCSV/zone/default/coordinate-transform owners, delete StageLightData cache/SceneLightState policy replacement and compat APIs. Keep only native allocation/destruction/CP932 fixes in classes. Current archive/parser/getAreaLightLightData providers are null/zero/no-op, zone initialization omitted, unknown zone mapping falls to stage default, and blend loses follow-camera coordinate conversion.','ResourceHolder LightData.arc and JMapInfo;StageLightSceneBinding and render/light/LightData must retire with OriginalSceneSupport;LightAreaHolder and ActorLightCtrl registration cleanup;real camera matrices;Aurora GX light uploads')
cfg('MaterialTextureModeCompat.cpp','src/Game/Util/ModelUtil.cpp','Restore four exact original texture-mode predicates to ModelUtil.','OriginalModelMaterialHelpers same owner;material headers')
cfg('OriginalImageEffectUtil.cpp','src/Game/Util/DrawUtil.cpp src/Game/Util/MathUtil.cpp','Restore original fillScreen helpers and lerp overloads to their own files. Preserve original green-channel expression even if it looks suspicious; donor matches.','DrawUtil other fragments;screen dimension provider;MathUtil symbols currently split')
cfg('OriginalJ2DProjection.cpp OriginalSceneDrawInit.cpp OriginalShadowTextureAccess.cpp OriginalShadowVolumeDraw.cpp','src/Game/Util/DrawUtil.cpp','Reunify original DrawUtil initialization/projection/shadow globals and draw functions in canonical owner. Preserve original constants; do not invent runtime wrappers.','Other DrawUtil fragments/providers;J2D graph;J3DSys canonical implementation;renderer dimensions')
cfg('OriginalJ3dJointTree.cpp OriginalJ3dJointTree.hpp','src/render/J3dMaterialRuntime.cpp src/JSystem/J3DGraphAnimator/J3DJointTree.cpp','Retain renderer-native resource storage/animation binding where J3dMaterialRuntime actually consumes it; eliminate copied link_joints hierarchy algorithm by invoking canonical makeHierarchy, and share canonical J3DSys traversal scope. Do not rename the adapter intact.','Native decoded J3dInfoSummary/JointBlockSummary;XanimeCore calculator;J3DJoint/MtxBuffer owner;scope migration','medium','needs-investigation')
cfg('OriginalJPADraw.cpp OriginalJPAFields.cpp OriginalJPAEmitterInit.cpp','src/Game/System/Overwrite.cpp','Restore original SMG overrides to Game/System/Overwrite.cpp (draw directions/billboards/stripes, fields, emitter init), not generic JParticle classes. Original game overrides intentionally call MR math. Keep only native user-work width/lifetime fields and constant trig/FP behavior.','Avoid base JParticle duplicate definitions;JPAResource dispatch tables;EffectKeeper callback retirement;mLastNonzeroUserWork native lifetime evidence;retain fp-contract=off')
cfg('OriginalModelLightAccess.cpp OriginalModelMaterialHelpers.cpp','src/Game/Util/ModelUtil.cpp src/Game/Util/LiveActorUtil.cpp','Restore per-symbol original ModelUtil/LiveActorUtil implementations; exact donor map identifies split utility ownership.','DisplayListMaker and ActorLightCtrl;other ModelUtil fragments;J3DMaterial providers')
# Real source-reference locations, favor use expressions over declarations and headers.
source=[]
for p in list((root/'src').rglob('*.cpp'))+list((root/'tests').rglob('*.cpp')):
 if '/compat/' in str(p):continue
 source.append((str(p.relative_to(root)),p.read_text(errors='replace').splitlines()))
rows=[]
for row in scan:
 name=Path(row['path']).name
 if name not in configs:raise RuntimeError(name)
 conf=configs[name].copy()
 conf['destination']=list(conf['destination'])
 donors=sorted(set(d['path'] for f in row['functions'] for d in f['same_symbol_donors']))
 if name.startswith('J3D') and name.endswith('.cpp'):
  conf['destination']=list(dict.fromkeys(conf['destination']+[d.removeprefix('decomp/') for d in donors]))
 names=[f['symbol'].split('::')[-1] for f in row['functions'] if len(f['symbol'].split('::')[-1])>7 and not f['symbol'].startswith('~')]
 if name.endswith('.hpp'):
  s=(root/row['path']).read_text();names+=re.findall(r'class\s+(\w+)',s)
 refs=[]
 call_pattern=re.compile(r'(?:->|\.|::)(?:'+ '|'.join(re.escape(sym) for sym in names) +r')\s*\(') if names else None
 for path,lines in source:
  for n,line in enumerate(lines,1):
   if name.endswith('.hpp') and f'compat/{name}' in line:
    refs.append({'path':path,'line':n,'text':line.strip(),'kind':'include'})
   elif call_pattern and call_pattern.search(line):
    refs.append({'path':path,'line':n,'text':line.strip(),'kind':'call expression'})
   if len(refs)>=12:break
  if len(refs)>=12:break
 if not refs:refs=[{'path':'src/Game/xmake.lua','line':90,'text':'add_files("../compat/**.cpp")','kind':'build provider; callers resolve public original symbols, see donor map'}]
 rows.append({'path':row['path'],**conf,'evidence':{'sha256':row['sha256'],'snapshot_matches':row['snapshot_matches'],'lines':row['line_count'],'review':'Full file text scan plus original-symbol body comparison and manual review of nonexact J3D diffs / Game-specific host implementations. Lexical matches are not semantic equivalence proof.','symbols':row['functions'],'original_donors':donors,'source_references':refs,'build':'src/Game/xmake.lua:90 wildcard includes compat CPP providers; remove each provider and add canonical owner once.'}})
assert len(rows)==80 and len({r['path'] for r in rows})==80
assert all(r['disposition']!='keep-general' for r in rows)
(notes/'render-effects-audit.json').write_text(json.dumps(rows,indent=2)+'\n')
print('wrote',len(rows),'rows',collections.Counter(r['disposition'] for r in rows))
print('nonexact scanner limitation: overloads and constructors/operators can be missed; human mappings override lexical donor guesses')
