#pragma once

#include "Game/Scene/SceneFunction.hpp"
#include "JSystem/JGeometry/TVec.hpp"

class LiveActor;
class LayoutActor;
class NameObj;
class NameObjGroup;
class JMapInfoIter;
class JMapInfo;
class ResourceHolder;
class StageSwitchCtrl;
struct ResTIMG;

namespace MR {
    bool isStageStateScenarioOpeningCamera();
    NameObjGroup* joinToNameObjGroup(NameObj*, const char*);
    void connectToSceneCollisionMapObj(LiveActor* pActor);
    void connectToSceneCollisionMapObjMovementCalcAnim(LiveActor* pActor);
    void connectToSceneCollisionMapObjWeakLight(LiveActor* pActor);
    void connectToSceneCollisionMapObjStrongLight(LiveActor* pActor);
    void connectToSceneCollisionEnemy(LiveActor* pActor);
    void connectToSceneCollisionEnemyMovement(NameObj* pObj);
    void connectToSceneCollisionEnemyStrongLight(LiveActor* pActor);
    void connectToSceneCollisionEnemyNoShadowedMapObjStrongLight(LiveActor* pActor);
    void connectToSceneNpc(LiveActor* pActor);
    void connectToSceneNpcMovement(LiveActor* pActor);
    void connectToSceneRide(LiveActor* pActor);
    void connectToSceneEnemy(LiveActor* pActor);
    void connectToSceneEnemyMovement(NameObj* pObj);
    void connectToSceneMapObj(LiveActor* pActor);
    void connectToSceneMapObjMovement(NameObj* pObj);
    void connectToSceneMapObjMovementCalcAnim(NameObj* pObj);
    void connectToSceneMapObjNoMovement(LiveActor* pActor);
    void connectToSceneMapObjNoCalcAnim(LiveActor* pActor);
    void connectToSceneMapObjNoCalcAnimStrongLight(LiveActor* pActor);
    void connectToSceneMapObjDecoration(LiveActor* pActor);
    void connectToSceneMapObjDecorationStrongLight(LiveActor* pActor);
    void connectToSceneMapObjDecorationMovement(NameObj* pObj);
    void connectToSceneMapObjStrongLight(LiveActor* pActor);
    void connectToSceneMapParts(LiveActor* pActor);
    void connectToScenePlanet(LiveActor* pActor);
    void connectToSceneEnvironment(LiveActor* pActor);
    void connectToSceneEnvironmentStrongLight(LiveActor* pActor);
    void connectToClippedMapParts(LiveActor* pActor);
    void connectToSceneEnemyDecoration(LiveActor* pActor);
    void connectToSceneEnemyDecorationMovement(NameObj* pObj);
    void connectToSceneEnemyDecorationMovementCalcAnim(NameObj* pObj);
    void connectToSceneItem(LiveActor* pActor);
    void connectToSceneItemStrongLight(LiveActor* pActor);
    void connectToSceneIndirectEnemy(LiveActor* pActor);
    void connectToSceneIndirectNpc(LiveActor* pActor);
    void connectToSceneIndirectMapObj(LiveActor* pActor);
    void connectToSceneIndirectMapObjStrongLight(LiveActor* pActor);
    void connectToSceneScreenEffectMovement(NameObj* pObj);
    void connectToSceneAreaObj(NameObj* pObj);
    void connectToScene3DModelFor2D(LiveActor* pActor);
    void connectToSceneLayout(NameObj* pObj);
    void connectToSceneLayoutMovementCalcAnim(NameObj* pObj);
    void connectToSceneLayoutDecoration(NameObj* pObj);
    void connectToSceneTalkLayout(NameObj* pObj);
    void connectToSceneTalkLayoutNoMovement(NameObj* pObj);
    void connectToSceneWipeLayout(NameObj* pObj);
    void connectToSceneLayoutOnPause(NameObj* pObj);
    void connectToSceneLayoutOnPauseNoMovement(NameObj* pObj);
    void connectToSceneLayoutOnPauseMovementCalcAnim(NameObj* pObj);
    void connectToSceneLayoutMovement(NameObj* pObj);
    void connectToSceneMovie(NameObj* pObj);
    void connectToSceneMirrorMapObj(LiveActor* pActor);
    void connectToSceneMirrorMapObjDecoration(LiveActor* pActor);
    void connectToSceneMirrorMapObjNoMovement(LiveActor* pActor);
    void connectToSceneCamera(NameObj* pObj);
    void connectToSceneNoShadowedMapObj(LiveActor* pActor);
    void connectToSceneNoShadowedMapObjStrongLight(LiveActor* pActor);
    void connectToSceneNoSilhouettedMapObj(LiveActor* pActor);
    void connectToSceneNoSilhouettedMapObjStrongLight(LiveActor* pActor);
    void connectToSceneNoSilhouettedMapObjWeakLightNoMovement(LiveActor* pActor);
    void connectToSceneSky(LiveActor* pActor);
    void connectToSceneAir(LiveActor* pActor);
    void connectToSceneSun(LiveActor* pActor);
    void connectToSceneCrystal(LiveActor* pActor);
    void connectToSceneNormalMapObj(LiveActor* pActor);

    bool isExistFileInArc(const ResourceHolder*, const char*, ...);
    JMapInfo* createCsvParser(const ResourceHolder*, const char*, ...);
    JMapInfo* tryCreateCsvParser(const LiveActor*, const char*, ...);
    JMapInfo* tryCreateCsvParser(const ResourceHolder*, const char*, ...);
    s32 getCsvDataElementNum(const JMapInfo*);
    void getCsvDataStr(const char**, const JMapInfo*, const char*, s32);
    void getCsvDataStrOrNULL(const char**, const JMapInfo*, const char*, s32);
    void getCsvDataS32(s32*, const JMapInfo*, const char*, s32);
    void getCsvDataU8(u8*, const JMapInfo*, const char*, s32);
    void getCsvDataF32(f32*, const JMapInfo*, const char*, s32);
    void getCsvDataBool(bool*, const JMapInfo*, const char*, s32);
    void getCsvDataVec(Vec*, const JMapInfo*, const char*, s32);

    const ResTIMG* loadTexFromArc(const char*, const char*);
    const ResTIMG* loadTexFromArc(const char*);
    class FunctorBase;

    bool isInWater(const TVec3f&);
    bool isInDeath(const TVec3f&);
    bool isInDarkMatter(const TVec3f&);
    void requestMovementOn(NameObj* pObj);
    void requestMovementOff(NameObj* pObj);
    bool isExistResourceInArc(const char* pArcName, const char* pResourceName);
    bool tryRumblePad(const void*, const char*, s32);
    bool tryRumblePadVeryStrongLong(const void*, s32);
    bool tryRumblePadVeryStrong(const void*, s32);
    bool tryRumblePadStrong(const void*, s32);
    bool tryRumblePadMiddle(const void*, s32);
    bool tryRumblePadWeak(const void*, s32);
    bool tryRumblePadVeryWeak(const void*, s32);
    bool tryRumbleDefaultHit(const void*, s32);
    void shakeCameraVeryStrong();
    void shakeCameraStrong();
    void shakeCameraNormalStrong();
    void shakeCameraNormal();
    void shakeCameraNormalWeak();
    void shakeCameraWeak();
    void shakeCameraVeryWeak();
    void declarePowerStarCoin100();
    void declareStarPiece(const NameObj* pObj, s32 num);
    void listenNameObjStageSwitchOnAppear(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&);
    void listenNameObjStageSwitchOnOffAppear(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&, const MR::FunctorBase&);
    void listenNameObjStageSwitchOnA(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&);
    void listenNameObjStageSwitchOnOffA(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&, const MR::FunctorBase&);
    void listenNameObjStageSwitchOnB(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&);
    void listenNameObjStageSwitchOffB(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&);
    void listenNameObjStageSwitchOnOffB(const NameObj*, const StageSwitchCtrl*, const MR::FunctorBase&, const MR::FunctorBase&);
}  // namespace MR
