function policy()
return {
    version = 1,
    markers = {
        integration_begin = "SMGPC_INTEGRATION_BEGIN",
        integration_end = "SMGPC_INTEGRATION_END",
        stub_macro = "SMGPC_STUB",
    },
    scope = {
        mirror_root = "src/game/Game",
        hard_fail_root = "src/game",
        render_rewrite_exceptions = {
            "src/render/",
            "src/game/layout/",
        },
    },
    decomp_needed = {
        p0 = {
            {
                upstream = "src/Game/Util/SoundUtil.cpp",
                status = "missing",
                blocking_features = "Stage/system sound parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Screen/LayoutManager.cpp",
                status = "missing",
                blocking_features = "Full layout actor manager parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Screen/PaneEffectKeeper.cpp",
                status = "missing",
                blocking_features = "Layout pane effect parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/System/WPadAcceleration.cpp",
                status = "missing",
                blocking_features = "WPad acceleration parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/System/WPadHVSwing.cpp",
                status = "missing",
                blocking_features = "WPad swing parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Effect/EffectSystemUtil.cpp",
                status = "missing",
                blocking_features = "Effect system utility parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Effect/MultiEmitter.cpp",
                status = "missing",
                blocking_features = "Layout effect emitter parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
        },
    },
    files = {
        {
            path = "src/game/Game/LiveActor/Nerve.cpp",
            upstream = "src/Game/LiveActor/Nerve.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Nerve.hpp",
            upstream = "include/Game/LiveActor/Nerve.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Spine.cpp",
            upstream = "src/Game/LiveActor/Spine.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Spine.hpp",
            upstream = "include/Game/LiveActor/Spine.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Map/FileSelectFunc.cpp",
            upstream = "src/Game/Map/FileSelectFunc.cpp",
            status = "pc-compat",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Map/FileSelectFunc.hpp",
            upstream = "include/Game/Map/FileSelectFunc.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Map/FileSelectIconID.cpp",
            upstream = "src/Game/Map/FileSelectIconID.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Map/FileSelectIconID.hpp",
            upstream = "include/Game/Map/FileSelectIconID.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/ButtonPaneController.cpp",
            upstream = "src/Game/Screen/ButtonPaneController.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/ButtonPaneController.hpp",
            upstream = "include/Game/Screen/ButtonPaneController.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/BackButton.cpp",
            upstream = "src/Game/Screen/BackButton.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/BackButton.hpp",
            upstream = "include/Game/Screen/BackButton.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectButton.cpp",
            upstream = "src/Game/Screen/FileSelectButton.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectButton.hpp",
            upstream = "include/Game/Screen/FileSelectButton.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectInfo.cpp",
            upstream = "src/Game/Screen/FileSelectInfo.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectInfo.hpp",
            upstream = "include/Game/Screen/FileSelectInfo.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectNumber.cpp",
            upstream = "src/Game/Screen/FileSelectNumber.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/FileSelectNumber.hpp",
            upstream = "include/Game/Screen/FileSelectNumber.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/IconAButton.cpp",
            upstream = "src/Game/Screen/IconAButton.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/IconAButton.hpp",
            upstream = "include/Game/Screen/IconAButton.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/InformationMessage.cpp",
            upstream = "src/Game/Screen/InformationMessage.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/InformationMessage.hpp",
            upstream = "include/Game/Screen/InformationMessage.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/LayoutActor.cpp",
            upstream = "src/Game/Screen/LayoutActor.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Screen/LayoutManager.cpp",
                "src/Game/Screen/PaneEffectKeeper.cpp",
            },
        },
        {
            path = "src/game/Game/Screen/LayoutActor.hpp",
            upstream = "include/Game/Screen/LayoutActor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/Manual2P.cpp",
            upstream = "src/Game/Screen/Manual2P.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/Manual2P.hpp",
            upstream = "include/Game/Screen/Manual2P.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/ProloguePictureBook.cpp",
            upstream = "src/Game/Screen/ProloguePictureBook.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/ProloguePictureBook.hpp",
            upstream = "include/Game/Screen/ProloguePictureBook.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SaveIcon.cpp",
            upstream = "src/Game/Screen/SaveIcon.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SaveIcon.hpp",
            upstream = "include/Game/Screen/SaveIcon.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SimpleLayout.cpp",
            upstream = "src/Game/Screen/SimpleLayout.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SimpleLayout.hpp",
            upstream = "include/Game/Screen/SimpleLayout.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SysInfoWindow.cpp",
            upstream = "src/Game/Screen/SysInfoWindow.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SysInfoWindow.hpp",
            upstream = "include/Game/Screen/SysInfoWindow.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/TitleSequenceProduct.cpp",
            upstream = "src/Game/Screen/TitleSequenceProduct.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/TitleSequenceProduct.hpp",
            upstream = "include/Game/Screen/TitleSequenceProduct.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/YesNoController.cpp",
            upstream = "src/Game/Screen/YesNoController.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/YesNoController.hpp",
            upstream = "include/Game/Screen/YesNoController.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NerveExecutor.cpp",
            upstream = "src/Game/System/NerveExecutor.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NerveExecutor.hpp",
            upstream = "include/Game/System/NerveExecutor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/BinaryDataChunkHolder.cpp",
            upstream = "src/Game/System/BinaryDataChunkHolder.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/BinaryDataChunkHolder.hpp",
            upstream = "include/Game/System/BinaryDataChunkHolder.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/BinaryDataContentAccessor.cpp",
            upstream = "src/Game/System/BinaryDataContentAccessor.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/BinaryDataContentAccessor.hpp",
            upstream = "include/Game/System/BinaryDataContentAccessor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataHolder.cpp",
            upstream = "src/Game/System/ConfigDataHolder.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataHolder.hpp",
            upstream = "include/Game/System/ConfigDataHolder.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataMii.cpp",
            upstream = "src/Game/System/ConfigDataMii.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataMii.hpp",
            upstream = "include/Game/System/ConfigDataMii.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataMisc.cpp",
            upstream = "src/Game/System/ConfigDataMisc.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/ConfigDataMisc.hpp",
            upstream = "include/Game/System/ConfigDataMisc.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/GameDataHolder.cpp",
            upstream = "src/Game/System/GameDataHolder.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/GameDataHolder.hpp",
            upstream = "include/Game/System/GameDataHolder.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/GameSequenceFunction.cpp",
            upstream = "src/Game/System/GameSequenceFunction.cpp",
            status = "pc-compat",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/GameSequenceFunction.hpp",
            upstream = "include/Game/System/GameSequenceFunction.hpp",
            status = "pc-compat",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NANDManager.cpp",
            upstream = "src/Game/System/NANDManager.cpp",
            status = "pc-compat",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NANDManager.hpp",
            upstream = "include/Game/System/NANDManager.hpp",
            status = "pc-compat",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataBannerCreator.cpp",
            upstream = "src/Game/System/SaveDataBannerCreator.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataBannerCreator.hpp",
            upstream = "include/Game/System/SaveDataBannerCreator.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataHandleSequence.cpp",
            upstream = "src/Game/System/SaveDataHandleSequence.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataHandleSequence.hpp",
            upstream = "include/Game/System/SaveDataHandleSequence.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataHandler.cpp",
            upstream = "src/Game/System/SaveDataHandler.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SaveDataHandler.hpp",
            upstream = "include/Game/System/SaveDataHandler.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SysConfigFile.cpp",
            upstream = "src/Game/System/SysConfigFile.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/SysConfigFile.hpp",
            upstream = "include/Game/System/SysConfigFile.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/UserFile.cpp",
            upstream = "src/Game/System/UserFile.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/UserFile.hpp",
            upstream = "include/Game/System/UserFile.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/FileUtil.cpp",
            upstream = "src/Game/Util/FileUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/FileUtil.hpp",
            upstream = "include/Game/Util/FileUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/Functor.hpp",
            upstream = "include/Game/Util/Functor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/GamePadUtil.cpp",
            upstream = "src/Game/Util/GamePadUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/System/WPadAcceleration.cpp",
                "src/Game/System/WPadHVSwing.cpp",
            },
        },
        {
            path = "src/game/Game/Util/GamePadUtil.hpp",
            upstream = "include/Game/Util/GamePadUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/HashUtil.cpp",
            upstream = "src/Game/Util/HashUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/BitArray.cpp",
            upstream = "src/Game/Util/BitArray.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/BitArray.hpp",
            upstream = "include/Game/Util/BitArray.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/HashUtil.hpp",
            upstream = "include/Game/Util/HashUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/LayoutUtil.cpp",
            upstream = "src/Game/Util/LayoutUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Effect/MultiEmitter.cpp",
            },
        },
        {
            path = "src/game/Game/Util/LayoutUtil.hpp",
            upstream = "include/Game/Util/LayoutUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/MemoryUtil.cpp",
            upstream = "src/Game/Util/MemoryUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/MemoryUtil.hpp",
            upstream = "include/Game/Util/MemoryUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/MessageUtil.cpp",
            upstream = "src/Game/Util/MessageUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/MessageUtil.hpp",
            upstream = "include/Game/Util/MessageUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/NerveUtil.cpp",
            upstream = "src/Game/Util/NerveUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/NerveUtil.hpp",
            upstream = "include/Game/Util/NerveUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/ObjUtil.cpp",
            upstream = "src/Game/Util/ObjUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Effect/EffectSystemUtil.cpp",
            },
        },
        {
            path = "src/game/Game/Util/ObjUtil.hpp",
            upstream = "include/Game/Util/ObjUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SoundUtil.cpp",
            upstream = "src/Game/Util/SoundUtil.cpp",
            status = "ported-stub",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Util/SoundUtil.cpp",
            },
        },
        {
            path = "src/game/Game/Util/SoundUtil.hpp",
            upstream = "include/Game/Util/SoundUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/StarPointerUtil.cpp",
            upstream = "src/Game/Util/StarPointerUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/StarPointerUtil.hpp",
            upstream = "include/Game/Util/StarPointerUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SystemUtil.cpp",
            upstream = "src/Game/Util/SystemUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SystemUtil.hpp",
            upstream = "include/Game/Util/SystemUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/TriggerChecker.cpp",
            upstream = "src/Game/Util/TriggerChecker.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/TriggerChecker.hpp",
            upstream = "include/Game/Util/TriggerChecker.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
    },
}
end
