function policy()
return {
    version = 1,
    markers = {
        integration_begin = "SMGPC_INTEGRATION_BEGIN",
        integration_end = "SMGPC_INTEGRATION_END",
        stub_macro = "SMGPC_STUB",
    },
    scope = {
        mirror_root = "src/game/Game",
        hard_fail_root = "src/game",
        render_rewrite_exceptions = {
            "src/render/",
            "src/game/layout/",
        },
    },
    decomp_needed = {
        p0 = {
            {
                upstream = "src/Game/Util/SoundUtil.cpp",
                status = "missing",
                blocking_features = "Stage/system sound parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Screen/LayoutManager.cpp",
                status = "missing",
                blocking_features = "Full layout actor manager parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Screen/PaneEffectKeeper.cpp",
                status = "missing",
                blocking_features = "Layout pane effect parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/System/WPadAcceleration.cpp",
                status = "missing",
                blocking_features = "WPad acceleration parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/System/WPadHVSwing.cpp",
                status = "missing",
                blocking_features = "WPad swing parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Effect/EffectSystemUtil.cpp",
                status = "missing",
                blocking_features = "Effect system utility parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
            {
                upstream = "src/Game/Effect/MultiEmitter.cpp",
                status = "missing",
                blocking_features = "Layout effect emitter parity",
                owner = "pc-port",
                last_update = "2026-02-13",
            },
        },
    },
    files = {
        {
            path = "src/game/Game/LiveActor/Nerve.cpp",
            upstream = "src/Game/LiveActor/Nerve.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Nerve.hpp",
            upstream = "include/Game/LiveActor/Nerve.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Spine.cpp",
            upstream = "src/Game/LiveActor/Spine.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/LiveActor/Spine.hpp",
            upstream = "include/Game/LiveActor/Spine.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/LayoutActor.cpp",
            upstream = "src/Game/Screen/LayoutActor.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Screen/LayoutManager.cpp",
                "src/Game/Screen/PaneEffectKeeper.cpp",
            },
        },
        {
            path = "src/game/Game/Screen/LayoutActor.hpp",
            upstream = "include/Game/Screen/LayoutActor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SimpleLayout.cpp",
            upstream = "src/Game/Screen/SimpleLayout.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/SimpleLayout.hpp",
            upstream = "include/Game/Screen/SimpleLayout.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/TitleSequenceProduct.cpp",
            upstream = "src/Game/Screen/TitleSequenceProduct.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Screen/TitleSequenceProduct.hpp",
            upstream = "include/Game/Screen/TitleSequenceProduct.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NerveExecutor.cpp",
            upstream = "src/Game/System/NerveExecutor.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/System/NerveExecutor.hpp",
            upstream = "include/Game/System/NerveExecutor.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/FileUtil.cpp",
            upstream = "src/Game/Util/FileUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/FileUtil.hpp",
            upstream = "include/Game/Util/FileUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/GamePadUtil.cpp",
            upstream = "src/Game/Util/GamePadUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/System/WPadAcceleration.cpp",
                "src/Game/System/WPadHVSwing.cpp",
            },
        },
        {
            path = "src/game/Game/Util/GamePadUtil.hpp",
            upstream = "include/Game/Util/GamePadUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/LayoutUtil.cpp",
            upstream = "src/Game/Util/LayoutUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Effect/MultiEmitter.cpp",
            },
        },
        {
            path = "src/game/Game/Util/LayoutUtil.hpp",
            upstream = "include/Game/Util/LayoutUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/NerveUtil.cpp",
            upstream = "src/Game/Util/NerveUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/NerveUtil.hpp",
            upstream = "include/Game/Util/NerveUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/ObjUtil.cpp",
            upstream = "src/Game/Util/ObjUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Effect/EffectSystemUtil.cpp",
            },
        },
        {
            path = "src/game/Game/Util/ObjUtil.hpp",
            upstream = "include/Game/Util/ObjUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SoundUtil.cpp",
            upstream = "src/Game/Util/SoundUtil.cpp",
            status = "ported-stub",
            owner = "pc-port",
            check_divergence = false,
            required_stub_symbols = {
                "src/Game/Util/SoundUtil.cpp",
            },
        },
        {
            path = "src/game/Game/Util/SoundUtil.hpp",
            upstream = "include/Game/Util/SoundUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SystemUtil.cpp",
            upstream = "src/Game/Util/SystemUtil.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/SystemUtil.hpp",
            upstream = "include/Game/Util/SystemUtil.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/TriggerChecker.cpp",
            upstream = "src/Game/Util/TriggerChecker.cpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
        {
            path = "src/game/Game/Util/TriggerChecker.hpp",
            upstream = "include/Game/Util/TriggerChecker.hpp",
            status = "partial",
            owner = "pc-port",
            check_divergence = false,
        },
    },
}
end
