#include "compat/Cp932Literal.hpp"
#include "Game/System/WPadRumbleData.hpp"
#include "Game/Util/HashUtil.hpp"
#include <revolution/wpad.h>

static RumblePattern gRumblePatternTable[] = {
    {
        CP932("最強【長】"),
        100,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        CP932("最強"),
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("強"),
        30,
        {
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("中"),
        30,
        {
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("弱"),
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("微弱"),
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("マリオ[スリップアップ]"),
        25,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        CP932("マリオ[亀投げ]"),
        10,
        {
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {
        CP932("マリオ[ホッパーため]"),
        5,
        {
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {
        CP932("マリオ[変身]"),
        60,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("マリオ[変身解除]"),
        30,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
        },
    },
    {
        CP932("マリオ[しびれ]"),
        60,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
        },
    },
    {
        CP932("マリオ[つぶれ]"),
        120,
        {
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,   WPAD_MOTOR_RUMBLE, WPAD_MOTOR_STOP,
            WPAD_MOTOR_RUMBLE,
        },
    },
    {},
};

namespace RumbleData {
    // FIXME: Register swaps.
    const RumblePattern* getPattern(const char* pName) {
        u32 hash = MR::getHashCode(pName);

        for (u32 i = 0; i < getTableSize(); i++) {
            const RumblePattern* pPattern = getData(i);

            if (hash != pPattern->mHash) {
                continue;
            }

            return pPattern;
        }

        return nullptr;
    }

    void initHashValue() {
        for (u32 i = 0; i < getTableSize(); i++) {
            RumblePattern* pPattern = getData(i);

            pPattern->mHash = MR::getHashCode(pPattern->mName);
        }
    }

    void checkHashCollision() {
    }

    u32 getTableSize() {
        return ARRAY_SIZE(gRumblePatternTable) - 1;
    }

    RumblePattern* getData(u16 index) {
        return &gRumblePatternTable[index];
    }
};  // namespace RumbleData
