#!/usr/bin/env python3
"""Extract original factory identity independently of native constructor availability."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'decomp/src/Game/NameObj/NameObjFactory.cpp'
OUTPUT = ROOT / 'src/scene/nameobj/OriginalNameObjNames.inc'


def render():
    source = SOURCE.read_text()
    marker = 'const NameObjFactory::Name2CreateFunc cCreateTable[] = {'
    begin = source.index(marker) + len(marker)
    end = source.index('\n    };', begin)
    table = source[begin:end]
    # All canonical rows have one three-field aggregate, with a literal name.
    rows = re.findall(r'\{\s*"([^"\\]+)"\s*,[^{}]*\}', table)
    if len(rows) != table.count('{') or len(rows) != table.count('}'):
        raise ValueError('Unsupported original factory row syntax; do not silently omit names')
    names = sorted(set(rows), key=str.casefold)
    return ('// Generated by scripts/generate_nameobj_catalog.py from original cCreateTable.\n'
            '// Identity only: no native constructors, fallback actors or availability policy.\n' +
            ''.join('    ' + json.dumps(name) + ',\n' for name in names))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = render()
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit('Original NameObj identity inventory is stale')
    else:
        OUTPUT.write_text(generated)
    print(f'Original factory identity inventory: {generated.count(chr(10)) - 2} names')


if __name__ == '__main__':
    main()
