#pragma once

#include <array>
#include <cstdint>
#include <memory>

#include <revolution.h>

#include "Game/LiveActor/LiveActor.hpp"
#include "Game/Map/FileSelectIconID.hpp"
#include "camera/CameraParam.hpp"

class FileSelectCameraController;
class FileSelectButton;
class FileSelectEffect;
class FileSelectInfo;
class FileSelectItem;
class FileSelectItemDelegatorBase;
class FileSelectSky;
class HitSensor;
class BackButton;
class BrosButton;
class InformationMessage;
class Manual2P;
class MiiConfirmIcon;
class MiiSelect;
class SysInfoWindow;
class TitleSequenceProduct;
class UserFile;

class FileSelector : public LiveActor {
public:
    explicit FileSelector(const char* pName = "ファイルセレクタ");
    ~FileSelector() override;

    void init(const JMapInfoIter& rIter) override;
    void appear() override;
    void kill() override;
    void control() override;
    bool receiveOtherMsg(u32 msg, HitSensor* pSender = nullptr, HitSensor* pReceiver = nullptr) override;

    void createCameraController();
    void createTitle();
    void createSky();
    void createMiiSelect();
    void createOperationButton();
    void createBackButton();
    void createBrosButton();
    void createInfoMessage();
    void createSysInfoWindow();
    void createFileInfo();
    void createMiiConfirmIcon();
    void createManual();
    void createSelectEffect();
    void createFileItems();
    void initUserFileArray();
    void initUserFile();
    void restoreUserFile();
    void checkAllComplete();
    void callbackStart();
    void callbackCopy();
    void callbackMii();
    void callbackDelete();
    void callbackManual();
    void setFileInfo(s32 fileNo);
    void setUserFileMario(s32 fileNo, bool isMario);
    void playSelectedME();
    void updateBgm();
    [[nodiscard]] bool isUserFileCorrupted(s32 fileNo) const;
    [[nodiscard]] bool isUserFileAppearLuigi(s32 fileNo) const;
    [[nodiscard]] bool isUserFileLuigi(s32 fileNo) const;
    [[nodiscard]] s32 getMissCount(s32 fileNo) const;
    void notifyItem(FileSelectItem* pItem, s32 action);
    [[nodiscard]] FileSelectIconID::EFellowID getUserFileFellowID(s32 fileNo) const;
    [[nodiscard]] bool isUserFileMiiIdValid(s32 fileNo) const;
    [[nodiscard]] s32 getUserFileMiiIndex(s32 fileNo) const;
    void storeSetMiiIdUserFile(s32 fileNo, const FileSelectIconID& rIconId);
    void getIconId(FileSelectIconID* pIconId, s32 fileNo) const;
    void onPoint(FileSelectItem* pItem);
    void onSelect(FileSelectItem* pItem);
    void updateFileInfo();
    void appearAllItems();
    void appearAllIndex();
    void disappearAllIndex();
    void initAllItems();
    void invalidateSelectAll();
    void validateSelectAll();
    void validateRotateAllItems();
    void disappearAllLayout();
    [[nodiscard]] bool isHiddenAllLayout() const;
    void clearPointing();
    bool checkSelectedBackButton();
    void calcBasePos(float ratio);
    void goToNearPoint();
    [[nodiscard]] FileSelectItem* getItemByFileNo(s32 fileNo) const;
    void exeWaitBind();
    void exeTitle();
    void exeTitleEnd();
    void exeRFLError();
    void exeRFLWait();
    void exeFileSelectStart();
    void exeFileSelect();
    void exeFileConfirmStart();
    void exeFileConfirm();
    void exeCreateConfirmStart();
    void exeCreateConfirm();
    void exeCreate();
    void exeDemoStartWait();
    void exeDemo();
    void exeCopyWait();
    void exeCopySelect();
    void exeCopyConfirmStart();
    void exeCopyConfirm();
    void exeCopySave();
    void exeCopySaveMii();
    void exeCopyDemo();
    void exeCopyRejectStart();
    void exeCopyReject();
    void exeMiiWait();
    void exeMiiSelectStart();
    void exeMiiSelect();
    void exeMiiCancel();
    void exeMiiConfirmWait();
    void exeMiiConfirm();
    void exeMiiCreateWait();
    void exeMiiCreateDemo();
    void exeMiiCaution();
    void exeMiiInfoStart();
    void exeMiiInfo();
    void exeDeleteConfirmStart();
    void exeDeleteConfirm();
    void exeDelete();
    void exeDeleteDemo();
    void exeManualStart();
    void exeManual();

#ifndef NDEBUG
    // SMGPC temporary debug observer API for runtime-scene tests and semantic traces.
    [[nodiscard]] std::uint64_t getSkyStep() const;
    [[nodiscard]] bool isTitleActive() const;
    [[nodiscard]] bool isTitleStarted() const;
    [[nodiscard]] bool isTitleEnded() const;
    [[nodiscard]] bool isCameraAtFarPoint() const;
    [[nodiscard]] bool isFileSelectStarted() const;
    [[nodiscard]] bool didAppearAllItems() const;
    [[nodiscard]] bool didInitAllItems() const;
    [[nodiscard]] bool didInvalidateSelectAll() const;
    [[nodiscard]] bool didValidateRotateAllItems() const;
    [[nodiscard]] float getBasePosRatio() const;
    [[nodiscard]] s32 getMiiValidIndexCollectionCount() const;
    [[nodiscard]] s32 getItemCount() const;
    [[nodiscard]] s32 getAppearedItemCount() const;
    [[nodiscard]] bool isItemNew(s32 index) const;
    [[nodiscard]] s32 getSelectInvalidItemCount() const;
    [[nodiscard]] s32 getRotateInvalidItemCount() const;
    [[nodiscard]] s32 getItemFileNo(s32 index) const;
    [[nodiscard]] bool isOperationButtonCreated() const;
    [[nodiscard]] bool isFileInfoCreated() const;
    [[nodiscard]] bool isBackButtonCreated() const;
    [[nodiscard]] bool isBrosButtonCreated() const;
    [[nodiscard]] bool isInfoMessageCreated() const;
    [[nodiscard]] bool isSysInfoWindowCreated() const;
    [[nodiscard]] bool isMiiConfirmIconCreated() const;
    [[nodiscard]] bool isManualCreated() const;
    [[nodiscard]] bool isSelectEffectCreated() const;
    [[nodiscard]] s32 getSelectEffectCount() const;
    [[nodiscard]] bool isOperationButtonAlive() const;
    [[nodiscard]] bool isFileInfoAlive() const;
    [[nodiscard]] bool wasStartCallbackCalled() const;
    [[nodiscard]] bool wasCopyCallbackCalled() const;
    [[nodiscard]] bool wasMiiCallbackCalled() const;
    [[nodiscard]] bool wasDeleteCallbackCalled() const;
    [[nodiscard]] bool wasManualCallbackCalled() const;
    [[nodiscard]] bool didClearPointing() const;
    [[nodiscard]] bool didStartDemoStartWait() const;
    [[nodiscard]] bool didStartCopyWait() const;
    [[nodiscard]] bool didStartCopySelect() const;
    [[nodiscard]] bool didStartCopyConfirmStart() const;
    [[nodiscard]] bool didStartCopyConfirm() const;
    [[nodiscard]] bool didStartCopySave() const;
    [[nodiscard]] bool didStartCopySaveMii() const;
    [[nodiscard]] bool didStartCopyDemo() const;
    [[nodiscard]] bool didStartCopyRejectStart() const;
    [[nodiscard]] bool didStartCopyReject() const;
    [[nodiscard]] bool didStartMiiWait() const;
    [[nodiscard]] bool didStartMiiSelectStart() const;
    [[nodiscard]] bool didStartMiiSelect() const;
    [[nodiscard]] bool didStartMiiConfirm() const;
    [[nodiscard]] bool didStartMiiCreateWait() const;
    [[nodiscard]] bool didStartMiiCreateDemo() const;
    [[nodiscard]] bool didStartDeleteConfirmStart() const;
    [[nodiscard]] bool didStartManualStart() const;
    [[nodiscard]] bool didStartManual() const;
    [[nodiscard]] bool didStartDemo() const;
    [[nodiscard]] bool didAppearAllIndex() const;
    [[nodiscard]] bool didDisappearAllIndex() const;
    [[nodiscard]] bool didStartFileConfirmStart() const;
    [[nodiscard]] bool didStartFileConfirm() const;
    [[nodiscard]] bool didStartCreateConfirmStart() const;
    [[nodiscard]] bool didStartCreateConfirm() const;
    [[nodiscard]] bool didStartCreate() const;
    [[nodiscard]] bool didStartDeleteConfirm() const;
    [[nodiscard]] bool didStartDelete() const;
    [[nodiscard]] bool didStartDeleteDemo() const;
    [[nodiscard]] bool isDemoStartWait() const;
    [[nodiscard]] bool isDemo() const;
    [[nodiscard]] bool isFileSelectStart() const;
    [[nodiscard]] bool isFileSelect() const;
    [[nodiscard]] bool isFileConfirmStart() const;
    [[nodiscard]] bool isFileConfirm() const;
    [[nodiscard]] bool isCreateConfirmStart() const;
    [[nodiscard]] bool isCreateConfirm() const;
    [[nodiscard]] bool isCreate() const;
    [[nodiscard]] bool isCopyWait() const;
    [[nodiscard]] bool isCopySelect() const;
    [[nodiscard]] bool isCopyConfirmStart() const;
    [[nodiscard]] bool isCopyConfirm() const;
    [[nodiscard]] bool isCopySave() const;
    [[nodiscard]] bool isCopySaveMii() const;
    [[nodiscard]] bool isCopyDemo() const;
    [[nodiscard]] bool isCopyRejectStart() const;
    [[nodiscard]] bool isCopyReject() const;
    [[nodiscard]] bool isMiiWait() const;
    [[nodiscard]] bool isMiiSelectStartFirst() const;
    [[nodiscard]] bool isMiiSelectStart() const;
    [[nodiscard]] bool isMiiSelect() const;
    [[nodiscard]] bool isMiiCancel() const;
    [[nodiscard]] bool isMiiConfirmWait() const;
    [[nodiscard]] bool isMiiConfirm() const;
    [[nodiscard]] bool isMiiCreateWait() const;
    [[nodiscard]] bool isMiiCreateDemo() const;
    [[nodiscard]] bool isMiiCaution() const;
    [[nodiscard]] bool isMiiInfoStart() const;
    [[nodiscard]] bool isMiiInfo() const;
    [[nodiscard]] bool isDeleteConfirmStart() const;
    [[nodiscard]] bool isDeleteConfirm() const;
    [[nodiscard]] bool isDelete() const;
    [[nodiscard]] bool isDeleteDemo() const;
    [[nodiscard]] bool isManualStart() const;
    [[nodiscard]] bool isManual() const;
    [[nodiscard]] s32 getSelectedFileNo() const;
    [[nodiscard]] s32 getPointedFileNo() const;
    [[nodiscard]] s32 getPreviousPointingFileNo() const;
    [[nodiscard]] s32 getCurrentFileInfoFileNo() const;
    [[nodiscard]] s32 getCurrentFileInfoMissCount() const;
    [[nodiscard]] bool isCurrentFileInfoSelectedMario() const;
    [[nodiscard]] const wchar_t* getCurrentFileInfoDateMessage() const;
    [[nodiscard]] const wchar_t* getCurrentFileInfoTimeMessage() const;
    [[nodiscard]] bool isCameraAtNearPoint() const;
    [[nodiscard]] bool wasItemPointed(s32 fileNo) const;
    [[nodiscard]] bool didItemTurnToFront(s32 fileNo) const;
    [[nodiscard]] s32 getItemTurnToFrontFrameCount(s32 fileNo) const;
    [[nodiscard]] const smgpc::camera::CameraParamVec3& getItemBasePosition(s32 index) const;
    [[nodiscard]] const TVec3f& getItemPosition(s32 index) const;
#endif

private:
    static constexpr s32 cItemCount = 6;

    std::unique_ptr< FileSelectCameraController > mCameraController;
    std::unique_ptr< TitleSequenceProduct > mTitleSeq;
    std::unique_ptr< FileSelectSky > mSky;
    std::unique_ptr< MiiSelect > mMiiSelect;
    std::unique_ptr< FileSelectButton > mSelectButton;
    std::unique_ptr< BackButton > mBackButton;
    std::unique_ptr< BrosButton > mBrosButton;
    std::unique_ptr< InformationMessage > mInfoMessage;
    std::unique_ptr< SysInfoWindow > mSysInfoWindow;
    std::unique_ptr< SysInfoWindow > mSysInfoWindowMini;
    std::unique_ptr< FileSelectInfo > mSelectInfo;
    std::unique_ptr< MiiConfirmIcon > mMiiConfirmIcon;
    std::unique_ptr< Manual2P > mManual2P;
    std::array< std::unique_ptr< FileSelectEffect >, cItemCount > mSelectEffects{};
    std::array< std::unique_ptr< UserFile >, cItemCount > mFiles{};
    std::array< std::unique_ptr< FileSelectItem >, cItemCount > mItems{};
    std::array< bool, cItemCount > mAllComplete{};
    std::unique_ptr< FileSelectItemDelegatorBase > mItemDelegator;
    std::array< smgpc::camera::CameraParamVec3, cItemCount > mItemBasePositions{};
    FileSelectItem* mSelectedItem = nullptr;
    FileSelectItem* mCopySourceItem = nullptr;
    FileSelectItem* mPointingItem = nullptr;
    FileSelectItem* mPreviousPointingItem = nullptr;
    float mBasePosRatio = 0.0F;
    s32 mSelectedFileNo = 1;
    s32 mCopySourceFileNo = 1;
    s32 mStageBgmState = 0;
    bool mIsFirstMiiSelection = false;
#ifndef NDEBUG
    // SMGPC temporary debug observer state; not part of release game code.
    bool mTitleStarted = false;
    bool mTitleEnded = false;
    bool mAllItemsAppeared = false;
    bool mAllItemsInitialized = false;
    bool mSelectAllInvalidated = false;
    bool mSelectAllInvalidatedOnce = false;
    bool mRotateAllItemsValidated = false;
    bool mFileSelectStarted = false;
    bool mStartCallbackCalled = false;
    bool mCopyCallbackCalled = false;
    bool mMiiCallbackCalled = false;
    bool mDeleteCallbackCalled = false;
    bool mManualCallbackCalled = false;
    bool mPointingCleared = false;
    bool mDemoStartWaitStarted = false;
    bool mCopyWaitStarted = false;
    bool mCopySelectStarted = false;
    bool mCopyConfirmStartStarted = false;
    bool mCopyConfirmStarted = false;
    bool mCopySaveStarted = false;
    bool mCopySaveMiiStarted = false;
    bool mCopyDemoStarted = false;
    bool mCopyRejectStartStarted = false;
    bool mCopyRejectStarted = false;
    bool mMiiWaitStarted = false;
    bool mMiiSelectStartStarted = false;
    bool mMiiSelectStarted = false;
    bool mMiiConfirmStarted = false;
    bool mMiiCreateWaitStarted = false;
    bool mMiiCreateDemoStarted = false;
    bool mDeleteConfirmStartStarted = false;
    bool mManualStartStarted = false;
    bool mManualStarted = false;
    bool mDemoStarted = false;
    bool mAllIndexAppeared = false;
    bool mAllIndexDisappeared = false;
    bool mFileConfirmStartStarted = false;
    bool mFileConfirmStarted = false;
    bool mCreateConfirmStartStarted = false;
    bool mCreateConfirmStarted = false;
    bool mCreateStarted = false;
    bool mDeleteConfirmStarted = false;
    bool mDeleteStarted = false;
    bool mDeleteDemoStarted = false;
#endif
};
