target("smg-pc-game")
    set_kind("static")
    add_cxxflags("-include " .. path.join(os.projectdir(), "src/compat/MetrowerksStdCompat.hpp"), { force = true })
    add_files("**.cpp")
    add_files("Gravity/PlanetGravityManager.cpp", {cxxflags = "-fpermissive"})
    add_files("GameAudio/AudStageBgmTable.cpp", {cxxflags = "-Wno-narrowing"})
    add_files("GameAudio/AudStageBgmWrap.cpp", {cxxflags = "-Wno-narrowing"})
    remove_files("AudioLib/AudBgmKeeper.cpp")
    remove_files("AudioLib/AudBgmMgr.cpp")
    remove_files("AudioLib/AudBgmRhythmStrategy.cpp")
    remove_files("AudioLib/AudFader.cpp")
    remove_files("AudioLib/AudTrackController.cpp")
    remove_files("AudioLib/AudWrap.cpp")
    remove_files("AreaObj/AreaObjContainer.cpp")
    remove_files("Screen/FileSelectInfo.cpp")
    remove_files("Screen/LayoutActor.cpp")
    remove_files("Screen/LayoutPaneCtrl.cpp")
    remove_files("Screen/SimpleLayout.cpp")
    remove_files("Screen/FullScreenBlur.cpp")
    remove_files("LiveActor/LodCtrl.cpp")
    remove_files("LiveActor/MaterialCtrl.cpp")
    remove_files("Map/FileSelectEffect.cpp")
    remove_files("Map/FileSelectFunc.cpp")
    remove_files("Map/FileSelectItem.cpp")
    remove_files("Map/FileSelector.cpp")
    remove_files("Map/FileSelectSky.cpp")
    remove_files("MapObj/StarPiece.cpp")
    remove_files("MapObj/StarPieceGroup.cpp")
    remove_files("NameObj/NameObjFactory.cpp")
    remove_files("Scene/SceneObjHolder.cpp")
    remove_files("System/StorySequenceExecutor.cpp")
    remove_files("System/GameDataFunction.cpp")
    remove_files("System/GameDataHolder.cpp")
    remove_files("System/SaveDataHandleSequence.cpp")
    remove_files("System/BinaryDataChunkHolder.cpp")
    remove_files("System/BinaryDataContentAccessor.cpp")
    remove_files("System/ConfigDataMisc.cpp")
    remove_files("System/GameDataTemporaryInGalaxy.cpp")
    remove_files("System/SysConfigFile.cpp")
    remove_files("Util/ActorSensorUtil.cpp")
    remove_files("Util/SequenceUtil.cpp")
    remove_files("Util/CameraUtil.cpp")
    remove_files("Util/GamePadUtil.cpp")
    remove_files("Util/GravityUtil.cpp")
    remove_files("Util/DemoUtil.cpp")
    remove_files("Util/EventUtil.cpp")
    remove_files("Util/FixedPosition.cpp")
    remove_files("Util/ActorMovementUtil.cpp")
    remove_files("Util/ActorShadowUtil.cpp")
    remove_files("Util/LiveActorUtil.cpp")
    remove_files("Util/JointController.cpp")
    remove_files("Util/MapUtil.cpp")
    remove_files("Util/MathUtil.cpp")
    remove_files("Util/MessageUtil.cpp")
    remove_files("Util/PlayerUtil.cpp")
    remove_files("Util/SceneUtil.cpp")
    remove_files("Util/SoundUtil.cpp")
    remove_files("Util/StringUtil.cpp")
    remove_files("Util/SystemUtil.cpp")
    remove_files("NPC/MiiFacePartsHolder.cpp")
    remove_files("NPC/MiiFaceParts.cpp")
    remove_files("NPC/MiiFaceRecipe.cpp")
    remove_files("NPC/NPCActor.cpp")
    add_files("../camera/**.cpp")
    add_files("../layout/**.cpp")
    add_files("../resource/**.cpp")
    add_files("../runtime/**.cpp")
    add_files("../scene/**.cpp")
    add_files("../compat/**.cpp")
    add_files {
        "../render/effects/JpcBillboard.cpp",
        "../render/effects/EffectResource.cpp",
        "../render/GXState.cpp",
        "../render/J3dAnimation.cpp",
        "../render/J3dMaterialRuntime.cpp",
        "../render/J3dMatrix.cpp",
        "../render/J3dModel.cpp",
        "../render/J3dModelRenderer.cpp",
        "../render/J3dTexture.cpp",
        "../render/JMathTrig.cpp",
        "../render/light/LightData.cpp",
        "../render/live_actor/LiveActorModel.cpp"
    }
    add_headerfiles("**.hpp")
    add_headerfiles("../camera/**.hpp")
    add_headerfiles("../layout/**.hpp")
    add_headerfiles("../resource/**.hpp")
    add_headerfiles("../runtime/**.hpp")
    add_headerfiles("../scene/**.hpp")
    add_headerfiles("../compat/**.hpp")
    add_headerfiles {
        "../render/effects/JpcBillboard.hpp",
        "../render/effects/EffectResource.hpp",
        "../render/GXState.hpp",
        "../render/J3dAnimation.hpp",
        "../render/J3dMaterialRuntime.hpp",
        "../render/J3dMatrix.hpp",
        "../render/J3dModel.hpp",
        "../render/J3dModelRenderer.hpp",
        "../render/J3dTexture.hpp",
        "../render/JMathTrig.hpp",
        "../render/light/LightData.hpp",
        "../render/live_actor/LiveActorModel.hpp"
    }
    add_includedirs("../", { public = true })
    add_deps {
        "smg-pc-common",
        "smg-pc-render",
        "aurora-nw4r",
        "aurora-card",
        "aurora-dvd",
        "aurora-gd",
        "aurora-gx",
        "aurora-ms",
        "aurora-mtx",
        "aurora-os",
        "aurora-pad",
        "aurora-vi"
    }
